(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)
(unless (package-installed-p 'use-package) (package-install 'use-package))
(require 'use-package)

(unless (package-installed-p 'undo-tree) (package-install 'undo-tree))
(require 'undo-tree)
(unless (package-installed-p 'evil) (package-install 'evil))
(require 'evil)
(evil-mode 1)
(setq-default evil-cross-lines t)

(unless (package-installed-p 'ayu-theme) (package-install 'ayu-theme))
(require 'ayu-theme)
(use-package ayu-theme :config (load-theme 'ayu-dark t))

(custom-set-variables '(package-selected-packages '(ayu-theme use-package evil)))
(custom-set-faces)

(menu-bar-mode -1)
(tool-bar-mode -1)
(show-paren-mode 1)
(global-linum-mode t)
(electric-pair-mode 1)
(prefer-coding-system 'utf-8)
(set-language-environment  'utf-8)
(setq-default tab-width 4 indent-tabs-mode nil)

(setq vc-follow-symlinks t)
(setq create-lockfiles nil)
(setq make-backup-files nil)
(setq inhibit-startup-message t)
(setq base16-theme-256-color-source "base16-shell")
