## ----------------------------------------
##	Brewfile
## ----------------------------------------
cask_args appdir: "/Applications"

## ========== Base ==========
brew "fd"
brew "jq"
brew "bat"
brew "exa"
brew "fzf"
brew "ghq"
brew "git"
brew "hub"
brew 'mas'
brew "nkf"
brew "tig"
brew "vim"
brew "grep"
brew "tmux"
brew "mycli"
brew "anyenv"
brew "neovim"
brew "ffmpeg"
brew "git-lfs"
brew "gnu-sed"
brew "ripgrep"
brew "hyperfine"
brew "brightness"
tap  "cjbassi/ytop"
brew "ytop"

## ========== Shell ==========
brew "zsh"
brew "zsh-completions"

## ========== Language ==========
brew "go"
brew "gcc"
brew "node", link: true
brew "perl"
brew "ruby"
brew "cmake"
brew "rbenv"
brew "python"
brew "pipenv"
brew "rustup"

## ========== Database ==========
brew "mysql"
brew "redis"
tap  "mongodb/brew"
brew "mongodb-community"

## ========== Fonts ==========
tap  "homebrew/cask-fonts"
cask "font-source-code-pro"
cask "font-noto-mono-for-powerline"

## ========== Applications ==========
cask "local"
cask "slack"
cask "alfred"
cask "docker"
cask "iterm2"
cask "kindle"
cask "skitch"
cask "zoomus"
cask "discord"
cask "postman"
cask "transmit"
cask "evernote"
cask "gpg-suite"
cask "rectangle"
cask "wireshark"
cask "appcleaner"
cask "burp-suite"
cask "sequel-pro"
cask "tor-browser"
cask "google-chrome"
cask "android-studio"
cask "mongodb-compass"
cask "karabiner-elements"
cask "visual-studio-code"
cask "google-japanese-ime"
cask "adobe-creative-cloud"
mas  "LINE", id: 539883307
mas  "Xcode", id: 497799835
mas  "Gifski", id: 1351639930
