## ----------------------------------------
##  Brewfile
## ----------------------------------------
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
cask_args appdir: "/Applications"

## ========== Base ==========
brew "fd"
brew "gh"
brew "sd"
brew "xz"
brew "act"
brew "bat"
brew "exa"
brew "fzf"
brew "ghq"
brew "git"
brew 'mas'
brew "nkf"
brew "dust"
brew "grep"
brew "tmux"
brew "shfmt"
brew "neovim"
brew "ffmpeg"
brew "rename"
brew "git-lfs"
brew "gnu-sed"
brew "ripgrep"
brew "lefthook"
brew "minikube"
brew "git-delta"
brew "shellcheck"
brew "youtube-dl"
brew "git-secrets"

## ========== Shell ==========
brew "zsh"
brew "zsh-completions"

## ========== Fonts ==========
tap  "homebrew/cask-fonts"
cask "font-fontawesome"
cask "font-hack-nerd-font"

## ========== Language ==========
brew "gcc"
brew "gdb"
brew "asdf"
brew "rustup"

## ========== Applications ==========
cask "gimp"
cask "zoom"
cask "slack"
cask "alfred"
cask "docker"
cask "kindle"
cask "iterm2"
cask "discord"
cask "postman"
cask "keycastr"
cask "gpg-suite"
cask "rectangle"
cask "ubersicht"
cask "appcleaner"
cask "sequel-ace"
cask "displaylink"
cask "google-chrome"
# cask "android-studio"
cask "karabiner-elements"
cask "visual-studio-code"
cask "google-japanese-ime"
# mas  "Xcode", id: 497799835
# mas "Amphetamine", id: 937984704
