## ----------------------------------------
##	Brewfile
## ----------------------------------------
cask_args appdir: "/Applications"

## ========== Base ==========
brew "fd"
brew "fx"
brew "jq"
brew "sd"
brew "bat"
brew "exa"
brew "fzf"
brew "ghq"
brew "git"
brew "hub"
brew 'mas'
brew "nkf"
brew "tig"
brew "vim"
brew "dust"
brew "grep"
brew "gron"
brew "tldr"
brew "tmux"
brew "mycli"
brew "neovim"
brew "ffmpeg"
brew "rename"
brew "git-lfs"
brew "gnu-sed"
brew "ripgrep"
brew "neofetch"
brew "git-delta"
brew "hyperfine"
brew "brightness"
brew "shellcheck"
brew "git-secrets"
brew "chromedriver"

## ========== Shell ==========
brew "zsh"
brew "zsh-completions"

## ========== Language ==========
brew "go"
brew "gcc"
brew "perl"
brew "node"
brew "ruby"
brew "cmake"
brew "cpanm"
brew "rustup"
brew "python@3.8"

## ========== Database ==========
brew "mysql"
brew "redis"
tap  "mongodb/brew"
brew "mongodb-community"

## ========== Fonts ==========
tap  "homebrew/cask-fonts"
cask "font-fontawesome"
cask "font-hack-nerd-font"

## ========== Applications ==========
cask "slack"
cask "alfred"
cask "docker"
cask "kindle"
cask "notion"
cask "skitch"
cask "zoomus"
cask "discord"
cask "postman"
cask "alacritty"
cask "cyberduck"
cask "gpg-suite"
cask "rectangle"
cask "ubersicht"
cask "appcleaner"
cask "sequel-pro"
cask "google-chrome"
cask "android-studio"
cask "mongodb-compass"
cask "karabiner-elements"
cask "visual-studio-code"
cask "google-japanese-ime"
cask "adobe-creative-cloud"
mas  "LINE", id: 539883307
mas  "Xcode", id: 497799835
mas  "Gifski", id: 1351639930
