#! /usr/local/bin/zsh

pattern='^(Add|Delete|Feature|Fix|Refactor|Doc)\([\S|\s]+\): [\S|\s]+[^.]$|^Merge'

if ! grep -P ${pattern} $1; then
	echo "Your commit message doesn't match pattern. Follow the pattern below."
	echo "<Type>(<file/func/arg>): <Task Name>"
	echo ""
	echo "<Body: What you cared and how you've changed.>"
	exit 1
fi
