#! /usr/local/bin/zsh

pattern='^(Add|Delete|Feature|Fix|Refactor|Update|Doc) [\S|\s]+[^.]$|^Merge|^Initial Commit'

if ! ggrep -P ${pattern} $1; then
	echo "Your commit message doesn't match pattern. Follow the pattern below."
	echo "<Type> <Task Name>(without period)"
	echo ""
	echo "<Body: What you cared and how you've changed.>"
	exit 1
fi
