#!/bin/bash

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

if [ -t 1 ] ; then
  exec < /dev/tty ; # <- enables interactive shell
fi

dir="$(git rev-parse --show-toplevel)"

call_lefthook()
{
  if lefthook -h >/dev/null 2>&1
  then
    eval lefthook $@
  elif test -f "$dir/node_modules/@arkweid/lefthook/bin/lefthook"
  then
    eval "$dir/node_modules/@arkweid/lefthook/bin/lefthook $@"
  elif bundle exec lefthook -h >/dev/null 2>&1
  then
    bundle exec lefthook $@
  elif npx @arkweid/lefthook -h >/dev/null 2>&1
  then
    npx @arkweid/lefthook $@
  elif yarn lefthook -h >/dev/null 2>&1
  then
    yarn lefthook $@
  else
    echo "Can't find lefthook in PATH"
  fi
}



call_lefthook "run pre-commit $@"

## ----------------------------------------
##  Checking
## ----------------------------------------
# Check for .pem files
MATCH=$(git diff --cached --name-only | grep '.*\.pem$')
if [[ ! -z $MATCH ]]; then
  echo "It looks like you're trying to commit a PEM file in:"
  echo "$MATCH\n\n"
  echo "Please check your code and remove any PEM files."
  exit 1
fi

# Check for large files
# filter=$(cat ~/.gitattributes | grep filter=lfs | awk '{printf "-e .%s$ ", $1}')
# files=($(git diff --cached --name-only --diff-filter=AM | grep -v $filter))
# gpath=$(git rev-parse --show-toplevel)
# for file in ${files}; do
#   file_size=$(ls -l ${gpath}/${file} | awk '{print $5}')
#   file_size_kb=$((file_size / 1024))
#   if [ ${file_size_kb} -ge 1024 ]; then
#     echo "${file} has size ${file_size_kb}KB over 1024KB. Please fix or avoit it to LFS."
#     exit 1
#   fi
# done
