#!/bin/sh

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

if [ -t 1 ] ; then
  exec < /dev/tty ; # <- enables interactive shell
fi

dir="$(cd "$(dirname "$(dirname "$(dirname "$0")")")" >/dev/null 2>&1 || exit ; pwd -P)"

call_lefthook()
{
  if lefthook -h >/dev/null 2>&1
  then
    eval $1
  elif test -f "$dir/node_modules/@arkweid/lefthook/bin/lefthook"
  then
    eval $dir/node_modules/@arkweid/lefthook/bin/$1
  elif bundle exec lefthook -h >/dev/null 2>&1
  then
    bundle exec $1
  elif npx lefthook -h >/dev/null 2>&1
  then
    npx $1
  elif yarn lefthook -h >/dev/null 2>&1
  then
    yarn $1
  else
    echo "Can't find lefthook in PATH"
  fi
}

# lefthook_version: a25d332481a8bb43fe436eb390e6e4c1

call_lefthook "lefthook install"

call_lefthook "lefthook run prepare-commit-msg $@"
